### ISSUE TITLE
Deixa seu projeto público

### ISSUE THREAD

**Issue by DavidGomesh** [PauloRobert0/sistema-de-campeonato#1]
# Como deixar o projeto público:

1. Entre no seu repositório;
2. Vá em configurações;
3. Desça a página até o final e clique em _**make private**_

![image](https://user-images.githubusercontent.com/53452408/83822371-32305900-a6a7-11ea-8f80-bca697bbcb3e.png)

**Comment by PauloRobert0** [comment]
> # Como deixar o projeto público:
> 1. Entre no seu repositório;
> 2. Vá em configurações;
> 3. Desça a página até o final e clique em _**make private**_
> 
> ![image](https://user-images.githubusercontent.com/53452408/83822371-32305900-a6a7-11ea-8f80-bca697bbcb3e.png)

# OK
vc que manda amado mestre
